/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        primary: "#cba6f7",
        secondary: "#313244",
        background: "#1e1e2e",
        base: "#1e1e2e",
        crust: "#11111b",
        surface: "#181825",
        border: "#45475a",
        foreground: "#cdd6f4",
        muted: "#6c7086",
        accent: "#89b4fa",
        destructive: "#f38ba8",
        success: "#a6e3a1",
        warning: "#fab387",
        green: "#a6e3a1",
        red: "#f38ba8",
        peach: "#fab387",
        blue: "#89b4fa",
        yellow: "#f9e2af",
        sky: "#89dceb",
        teal: "#94e2d5",
        pink: "#f5c2e7",
        mauve: "#cba6f7",
        lavender: "#b4befe",
        rosewater: "#f5e0dc",
        flamingo: "#f2cdcd",
        maroon: "#eba0ac",
        sapphire: "#74c7ec",
      },
    },
  },
  plugins: [],
};
